## Telco Customer Churn Prediction

This project builds a Logistic Regression model to predict whether a customer will churn based on demographic, service usage, and billing information.

Key steps:
- Data cleaning
- Feature encoding
- Feature scaling
- Logistic Regression model training
- Model evaluation using classification metrics

import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Telco-Customer-Churn.csv')

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [5]:
df.describe()

,SeniorCitizen,tenure,MonthlyCharges
count,7043.000000,7043.000000,7043.000000
mean,0.162147,32.371149,64.761692
std,0.368612,24.559481,30.090047
min,0.000000,0.000000,18.250000
25%,0.000000,9.000000,35.500000
50%,0.000000,29.000000,70.350000
75%,0.000000,55.000000,89.850000
max,1.000000,72.000000,118.750000


In [6]:
df.shape

(7043, 21)

In [7]:
df['Churn'].value_counts()

No     5174
Yes    1869
Name: Churn, dtype: int64

In [8]:
df['customerID'].nunique()

7043

In [9]:
df = df.drop(columns=['customerID'])

In [10]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [11]:
pd.crosstab(df['gender'],df['Churn'],normalize=True)*100

Churn,No,Yes
gender,,
Female,36.191964,13.332387
Male,37.271049,13.204600


In [12]:
pd.crosstab(df['SeniorCitizen'],df['Churn'],normalize=True)*100

Churn,No,Yes
SeniorCitizen,,
0,64.006815,19.778503
1,9.456198,6.758484


In [13]:
pd.crosstab(df['Partner'],df['Churn'],normalize=True)*100

Churn,No,Yes
Partner,,
No,34.658526,17.038194
Yes,38.804487,9.498793


In [14]:
pd.crosstab(df['Dependents'],df['Churn'],normalize=True)*100

Churn,No,Yes
Dependents,,
No,48.132898,21.908278
Yes,25.330115,4.628709


In [15]:
df.MultipleLines.unique()

array(['No phone service', 'No', 'Yes'], dtype=object)

In [16]:
df.InternetService.unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [17]:
df.OnlineSecurity.unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [18]:
df.OnlineBackup.unique()

array(['Yes', 'No', 'No internet service'], dtype=object)

In [19]:
df.Contract.unique()

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

In [20]:
df.PaymentMethod.unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [21]:
df.MultipleLines.unique()

array(['No phone service', 'No', 'Yes'], dtype=object)

We go on to map the columns

In [22]:
df['gender'] = df.gender.map({'Female':0,'Male':1})
df['Partner'] = df.Partner.map({'No':0,'Yes':1})
df['Dependents'] = df.Dependents.map({'No':0,'Yes':1})
df['PhoneService'] = df.PhoneService.map({'No':0,'Yes':1})
df.PaperlessBilling = df.PaperlessBilling.map({'No':0,'Yes':1})
df.Churn = df.Churn.map({'No':0,'Yes':1})

In [23]:
df = pd.get_dummies(df,columns=['PaymentMethod','Contract','StreamingMovies','StreamingTV','TechSupport','DeviceProtection','OnlineBackup','OnlineSecurity','InternetService','MultipleLines'],drop_first=True)

In [24]:
df['TotalCharges'] = df['TotalCharges'].replace(' ', np.nan)

In [25]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'])

In [26]:
df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [28]:
X = df.drop(columns=['Churn'])
y = df.Churn

In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,stratify=y,test_size=0.2)

In [30]:
(X_train == ' ').sum()

gender                                   0
SeniorCitizen                            0
Partner                                  0
Dependents                               0
tenure                                   0
PhoneService                             0
PaperlessBilling                         0
MonthlyCharges                           0
TotalCharges                             0
PaymentMethod_Credit card (automatic)    0
PaymentMethod_Electronic check           0
PaymentMethod_Mailed check               0
Contract_One year                        0
Contract_Two year                        0
StreamingMovies_No internet service      0
StreamingMovies_Yes                      0
StreamingTV_No internet service          0
StreamingTV_Yes                          0
TechSupport_No internet service          0
TechSupport_Yes                          0
DeviceProtection_No internet service     0
DeviceProtection_Yes                     0
OnlineBackup_No internet service         0
OnlineBacku

In [31]:
scaler = StandardScaler()

In [32]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [33]:
model = LogisticRegression(
    max_iter=2000,
    random_state=42,
    class_weight='balanced'
)

In [34]:
model.fit(X_train_scaled,y_train)

LogisticRegression(class_weight='balanced', max_iter=2000, random_state=42)

In [35]:
model.predict(X_test_scaled)

array([0, 1, 0, ..., 0, 0, 0])

In [36]:
model.score(X_test_scaled,y_test)

0.7395315826827538

In [37]:
y_pred = model.predict(X_test_scaled)

In [38]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.72      0.80      1035
           1       0.51      0.78      0.61       374

    accuracy                           0.74      1409
   macro avg       0.70      0.75      0.71      1409
weighted avg       0.80      0.74      0.75      1409



In [39]:
confusion_matrix(y_test,y_pred)

array([[749, 286],
       [ 81, 293]])

In [40]:
coef_df = pd.DataFrame({
    'Features':X.columns,
    'Coefficient': model.coef_[0]
})
coef_df

,Features,Coefficient
0,gender,0.016286
1,SeniorCitizen,0.056397
2,Partner,0.008679
3,Dependents,-0.105354
4,tenure,-1.140109
5,PhoneService,0.024760
6,PaperlessBilling,0.164701
7,MonthlyCharges,-1.036185
8,TotalCharges,0.473531
9,PaymentMethod_Credit card (automatic),0.000070


In [41]:
scaler = StandardScaler()

In [42]:
x = df.drop(columns=['PhoneService','PaymentMethod_Credit card (automatic)','Partner','Churn'])
y = df.Churn

In [43]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,stratify=y,test_size=0.2)

In [45]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [46]:
from sklearn.linear_model import LogisticRegression

model_l1 = LogisticRegression(
    penalty='l1',
    solver='liblinear',
    class_weight='balanced',
    max_iter=2000
)

model_l1.fit(x_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=2000, penalty='l1',
                   solver='liblinear')

In [50]:
model_l1.predict(x_test_scaled)

array([0, 1, 0, ..., 0, 0, 0])

In [53]:
model_l1.score(x_test_scaled,y_test)

0.7381121362668559

In [54]:
y_pred = model_l1.predict(x_test_scaled)

In [55]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.72      0.80      1035
           1       0.50      0.79      0.61       374

    accuracy                           0.74      1409
   macro avg       0.70      0.75      0.71      1409
weighted avg       0.80      0.74      0.75      1409



In [56]:
confusion_matrix(y_test,y_pred)

array([[746, 289],
       [ 80, 294]])

In [58]:
import pandas as pd

coef = pd.DataFrame({
    "Feature": x.columns,
    "Coefficient": model_l1.coef_[0]
})

coef

,Feature,Coefficient
0,gender,0.015194
1,SeniorCitizen,0.056584
2,Dependents,-0.100634
3,tenure,-1.127626
4,PaperlessBilling,0.164317
5,MonthlyCharges,-0.668867
6,TotalCharges,0.460013
7,PaymentMethod_Electronic check,0.188488
8,PaymentMethod_Mailed check,0.019787
9,Contract_One year,-0.295794


## Model Interpretation

Key drivers of churn include:

• Tenure (longer tenure reduces churn)
• InternetService_Fiber optic
• MonthlyCharges
• Contract length

Customers with short tenure and high monthly charges are more likely to churn.